### PR TITLE
[TEMP] shinano: disable build keystore.msm8974

### PR DESCRIPTION
**Pull request by alviteri**
It is causing FC when enter to settings - security options and soft reboots when unnistall an app

Signed-off-by: David Viteri <davidteri91@gmail.com>

@jerpelea probably the same is needed on 8226 due to 8994 has not this problem ..... and I can't check on 8226 device due to missing targets

### CODE REVIEW

**Comment by alviteri** [comment]
@erikcas are you having the mentioned issues on 8226?

**Comment by erikcas** [comment]
Will build for Eagle cannot confirm nor deny

**Comment by alviteri** [comment]
Ok be sure your device is using keystore because I think all Yukon isn't using it :) 

Thanks

**Comment by erikcas** [comment]
;-)

**Pull request closed without merging**
