### PR TITLE
shinano: update media files

### PR DESCRIPTION
**Pull request by alviteri**
this fixes 480p at original size .... adds qcif (based on copper

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
shoukd be splitted in several patches

**Comment by alviteri** [comment]
splitted ... check and tell me what do you think

**Comment by alviteri** [comment]
same are supported by rhine

**Comment by rancidfrog** [comment]
https://github.com/rcstar6696/device-sony-shinano/pull/3
Why isn't this included?

**Comment by alviteri** [comment]
because there is hevc.secure now
and we need to be sure 8974pro supports it

**Pull request closed without merging**
