### PR TITLE
shinano: enable Doze mode (Ambient Display)

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@erikcas
@humberos 

can you please test this on your targets too 

Thanks

**Comment by humberos** [comment]
I did it once long time ago :P
https://github.com/omnirom/android_device_sony_shinano-common/commit/81af2ba4b620c6e6dc30330e977dd06bea4d519f
Seems that it drains battery faster.

**Comment by humberos** [comment]
anyway, I think may doze performs better on android M than L.

**Comment by alviteri** [comment]
because it is a switchbutton .... user can decide if enable it or not

**Comment by alviteri** [comment]
also look your implementation has double integer parameter

https://github.com/omnirom/android_device_sony_shinano-common/blob/81af2ba4b620c6e6dc30330e977dd06bea4d519f/overlay/frameworks/base/core/res/res/values/config.xml#L87

**Comment by humberos** [comment]
yeah! it is.
I think it is ok to merge!
+1

**Comment by alviteri** [comment]
I am not sure about this but I think this is a omni feature and not on aosp

https://github.com/omnirom/android_device_sony_shinano-common/commit/81af2ba4b620c6e6dc30330e977dd06bea4d519f#diff-d0b0b2fa3d94fa65407daaa0f11d388cR22

**Comment by humberos** [comment]
https://gerrit.omnirom.org/#/c/11928

**Comment by alviteri** [comment]
ya that xD

**Comment by alviteri** [comment]
waiting for @jerpelea's answer  then

**Pull request closed without merging**
