### PR TITLE
shinano: Sources cleanup

### PR DESCRIPTION
**Pull request by humberos**
Fix code style

Signed-off-by: Humberto Borba <humberos@gmail.com>

### CODE REVIEW

**Comment by jerpelea** [comment]
same cleanup is needed on all devices to align them

**Comment by humberos** [comment]
Ok!
I will check all devices sources.

**Comment by humberos** [comment]
All common repos (kitakami, rhine, shinano and yukon) are ready to review/merge process.

**Comment by jerpelea** [comment]
please rebase

**Comment by humberos** [comment]
Done.

**Pull request merged**
