### PR TITLE
shinano: Update kernel headers

### PR DESCRIPTION
**Pull request by humberos**
Update kernel readers by using current kernel sources.

Signed-off-by: Humberto Borba <humberos@gmail.com>

### CODE REVIEW

**Comment by humberos** [comment]
Not sure but I think may it is required mainly for vidc.

**Comment by alviteri** [comment]
@humberos if this is merge probably the same for rhine and yukon

**Comment by humberos** [comment]
Well, if UBWC is required for vidc fix then we'll have a lot of work to do! :(

https://github.com/humberos/android_hardware_qcom_display/commit/65e26307e63ea672332aa5cea963ad630aaf95bf

**Comment by alviteri** [comment]
well, https://github.com/sonyxperiadev/kernel/commit/5595d14f687383550b0c21a127fe9169249483cc

**Comment by humberos** [comment]
@alviteri, display HAL needs it if it is required for vidc fix .

**Comment by alviteri** [comment]
@humberos maybe checking msm8084 hal we can find anything due to shamu is using same 3.10 kernel (obviously not the same as us but is a good reference) but I checked cm kernel because I can't find aosp sources and shamu doesn't has this https://github.com/sonyxperiadev/kernel/commit/5595d14f687383550b0c21a127fe9169249483cc so we can adapt few commits for 8074 to 8974 (about color formats and alignment)

**Comment by humberos** [comment]
@alviteri actually aosp msm8084 is more closer with CAF sources than aosp msm8974. Still thinking that we'll have a lot of work to do "or" we can try to bring back old adreno blobs.

**Comment by alviteri** [comment]
@humberos 

hardware/qcom/display/liboverlay/overlayUtils.cpp:153:24: error: 'MDP_RGBA_8888_UBWC' was not declared in this scope
                 return MDP_RGBA_8888_UBWC;
                        ^
hardware/qcom/display/liboverlay/overlayUtils.cpp:155:24: error: 'MDP_RGB_565_UBWC' was not declared in this scope
                 return MDP_RGB_565_UBWC;
                        ^
hardware/qcom/display/liboverlay/overlayUtils.cpp:159:24: error: 'MDP_Y_CBCR_H2V2_UBWC' was not declared in this scope
                 return MDP_Y_CBCR_H2V2_UBWC;

any ideas?

**Comment by jerpelea** [comment]
headers are already updated and moved to uapi

**Pull request closed without merging**
